using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Threading;
using NUnitTask = System.Threading.Tasks.Task;
using ChatdollKit.SpeechPipeline.VAD.Silero.Onnx;
using NUnit.Framework;

namespace ChatdollKit.Tests.SpeechPipeline.Onnx
{
    public class OnnxSileroVadModelTests
    {
        private const string ReferenceModelHash = "a4a068cd6cf1ea8355b84327595838ca748ec29a25bc91fc82e6c299ccdc5808";

        [TestCase(16000)]
        [TestCase(8000)]
        public void FrameProbabilitiesMatchPythonWrapper(int sampleRate)
        {
            var bytes = ReadModel();
            using (var sha = SHA256.Create())
            {
                var hash = BitConverter.ToString(sha.ComputeHash(bytes)).Replace("-", "").ToLowerInvariant();
                if (hash != ReferenceModelHash)
                {
                    Assert.Ignore("The Python reference probabilities require the documented model SHA-256.");
                }
            }

            // Generated by Silero 6.0.0 OnnxWrapper (CPU, ORT 1.21.1) with this
            // model and CreateFrames' exact PCM sequence, including silent frames.
            var expected = sampleRate == 16000
                ? new[] { 0.01201203465f, 0.05746787786f, 0.05079486966f, 0.04458412528f, 0.03277337551f, 0.01497119665f,
                    0.01267051697f, 0.0168544054f, 0.02390763164f, 0.01497945189f, 0.004746317863f, 0.006074130535f }
                : new[] { 0.005321055651f, 0.008907079697f, 0.01409497857f, 0.02212440968f, 0.005745410919f, 0.003769934177f,
                    0.01101842523f, 0.0044272542f, 0.000635176897f, 0.008609205484f, 0.001866310835f, 0.002747178078f };

            using (var model = new OnnxSileroVadModel(bytes))
            {
                var actual = CreateFrames(sampleRate, expected.Length).Select(frame => model.Predict(frame, sampleRate)).ToArray();
                Assert.That(actual, Is.EqualTo(expected).Within(0.00001f));
            }
        }

        [Test]
        public async NUnitTask AsyncPredictionMatchesSynchronousPredictionAndSkipsCanceledInput()
        {
            var bytes = ReadModel();
            using (var tested = new OnnxSileroVadModel(bytes))
            using (var reference = new OnnxSileroVadModel(bytes))
            using (var cancellation = new CancellationTokenSource())
            {
                var frames = CreateFrames(16000, 3).ToArray();
                Assert.That(await tested.PredictAsync(frames[0], 16000), Is.EqualTo(reference.Predict(frames[0], 16000)).Within(0.000001f));
                cancellation.Cancel();
                await SpeechAsyncAssert.ThrowsAsync<OperationCanceledException>(async () =>
                    await tested.PredictAsync(frames[1], 16000, cancellation.Token));
                for (var i = 1; i < frames.Length; i++)
                    Assert.That(await tested.PredictAsync(frames[i], 16000), Is.EqualTo(reference.Predict(frames[i], 16000)).Within(0.000001f));
            }
        }

        [Test]
        public void ResetRestoresTheOriginalPredictionSequence()
        {
            using (var model = new OnnxSileroVadModel(ReadModel()))
            {
                var frames = CreateFrames(16000, 8).ToArray();
                var first = frames.Select(frame => model.Predict(frame, 16000)).ToArray();
                model.ResetStates();
                var second = frames.Select(frame => model.Predict(frame, 16000)).ToArray();
                Assert.That(second, Is.EqualTo(first).Within(0.000001f));
            }
        }

        [Test]
        public void ChangingSampleRateResetsStateAndContext()
        {
            var bytes = ReadModel();
            using (var changing = new OnnxSileroVadModel(bytes))
            using (var fresh8k = new OnnxSileroVadModel(bytes))
            using (var fresh16k = new OnnxSileroVadModel(bytes))
            {
                foreach (var frame in CreateFrames(16000, 4)) changing.Predict(frame, 16000);
                foreach (var frame in CreateFrames(8000, 4))
                {
                    Assert.That(changing.Predict(frame, 8000), Is.EqualTo(fresh8k.Predict(frame, 8000)).Within(0.000001f));
                }
                foreach (var frame in CreateFrames(16000, 4))
                {
                    Assert.That(changing.Predict(frame, 16000), Is.EqualTo(fresh16k.Predict(frame, 16000)).Within(0.000001f));
                }
            }
        }

        [Test]
        public void InvalidInputDoesNotAdvanceAnExistingStream()
        {
            var bytes = ReadModel();
            using (var tested = new OnnxSileroVadModel(bytes))
            using (var reference = new OnnxSileroVadModel(bytes))
            {
                var frames = CreateFrames(16000, 3).ToArray();
                tested.Predict(frames[0], 16000);
                reference.Predict(frames[0], 16000);
                Assert.Throws<ArgumentNullException>(() => tested.Predict(null, 16000));
                Assert.Throws<ArgumentOutOfRangeException>(() => tested.Predict(frames[0], 44100));
                Assert.Throws<ArgumentException>(() => tested.Predict(new float[511], 16000));
                Assert.Throws<ArgumentException>(() => tested.Predict(new float[512], 8000));
                for (var i = 1; i < frames.Length; i++)
                {
                    Assert.That(tested.Predict(frames[i], 16000), Is.EqualTo(reference.Predict(frames[i], 16000)).Within(0.000001f));
                }
            }
        }

        [Test]
        public void ModelInstancesKeepIndependentState()
        {
            var bytes = ReadModel();
            using (var first = new OnnxSileroVadModel(bytes))
            using (var second = new OnnxSileroVadModel(bytes))
            using (var reference = new OnnxSileroVadModel(bytes))
            {
                foreach (var frame in CreateFrames(16000, 8))
                {
                    var expected = reference.Predict(frame, 16000);
                    Assert.That(first.Predict(frame, 16000), Is.EqualTo(expected).Within(0.000001f));
                    second.ResetStates();
                    second.Predict(frame, 16000);
                }
            }
        }

        [Test]
        public void DisposeIsIdempotentAndRejectsFurtherUse()
        {
            var model = new OnnxSileroVadModel(ReadModel());
            model.Dispose();
            Assert.DoesNotThrow(() => model.Dispose());
            Assert.Throws<ObjectDisposedException>(() => model.Predict(new float[512], 16000));
            Assert.Throws<ObjectDisposedException>(() => model.ResetStates());
        }

        [Test]
        public void ConstructorRejectsEmptyBytesAndInvalidThreadCounts()
        {
            Assert.Throws<ArgumentNullException>(() => new OnnxSileroVadModel((byte[])null));
            Assert.Throws<ArgumentException>(() => new OnnxSileroVadModel(Array.Empty<byte>()));
            Assert.Throws<ArgumentOutOfRangeException>(() => new OnnxSileroVadModel(new byte[] { 1 }, intraOpNumThreads: 0));
            Assert.Throws<ArgumentOutOfRangeException>(() => new OnnxSileroVadModel(new byte[] { 1 }, interOpNumThreads: 0));
        }

        private static byte[] ReadModel()
        {
            var path = Environment.GetEnvironmentVariable("CHATDOLLKIT_SILERO_MODEL_PATH");
            if (string.IsNullOrEmpty(path)) path = Path.Combine("Assets", "StreamingAssets", "silero_vad.onnx");
            if (!File.Exists(path)) Assert.Ignore("Set CHATDOLLKIT_SILERO_MODEL_PATH to run native Silero integration tests.");
            return File.ReadAllBytes(path);
        }

        private static IEnumerable<float[]> CreateFrames(int sampleRate, int count)
        {
            uint random = 123456789;
            for (var frame = 0; frame < count; frame++)
            {
                var samples = new float[sampleRate == 16000 ? 512 : 256];
                for (var i = 0; i < samples.Length; i++)
                {
                    random = unchecked(1664525 * random + 1013904223);
                    var pcm = (int)(random >> 16) - 32768;
                    samples[i] = frame % 4 == 0 ? 0f : pcm / 32768f;
                }
                yield return samples;
            }
        }
    }
}
